_config:
  _metadata:
    name: redis
    version: 4.0.6
    description: | 
      Redis is an open source (BSD licensed), in-memory data structure store, 
      used as a database, cache and message broker. 
      It supports data structures such as strings, hashes, lists, sets, 
      sorted sets with range queries, bitmaps, hyperloglogs and geospatial indexes with radius queries. 
      Redis has built-in replication, Lua scripting, LRU eviction, transactions and 
      different levels of on-disk persistence, and provides high availability via Redis Sentinel and 
      automatic partitioning with Redis Cluster.
  controllers:
  - containers:
    - image: cargo.caicloudprivatetest.com/library/redis:4.0.6-alpine
      imagePullPolicy: Always
      mounts:
      - name: data
        path: "/data"
      resources:
        limits:
          cpu: 0.2
          memory: 200Mi
        requests:
          cpu: 0.5
          memory: 512Mi
    controller:
      replica: 1
      strategy:
        surge: 1
        unavailable: 0
    pod:
      dns: ClusterFirst
      host:
        ipc: false
        network: false
        pid: false
      restart: Always
      termination: 30
    services:
    - name: redis
      type: ClusterIP
      ports:
      - protocol: HTTP
        targetPort: 6379
        port: 6379
    type: Deployment
    volumes:
    - name: data
      source:
        modes:
        - ReadWriteMany
      storage:
        request: 10Gi
        limit: 20Gi
      type: Scratch
