_config:
  _metadata:
    name: template
    version: 1.0.0
    description: "A basic template for application"
    creationTime: "2017-07-14 12:00:00"
    source: "/library/template/1.0.0"
    revision: 1
    appVersion: v1
    class: Default
    template:
      type: "template.caicloud.io/application"
      version: 1.0.0
  controllers:
  - type: StatefulSet
    controller:
      replica: 3
      name: "asda2222"
      domain: "asdas"
      annotations:
      - key: "controller.caicloud.io/feature-1.0.0"
        value: "{'test':'controller'}"
    schedule:
      labels:
        cpu: heavy
        io: heavy
      affinity:
        node:
          type: Prefered
          terms:
          - weight: 10
            expressions:
            - key: cpu
              operator: NotIn
              values:
              - heavy
              - midium
        pod:
          type: Required
          terms:
          - selector:
              labels:
                cpu: heavy
      antiaffinity:
        pod:
          type: Prefered
          terms:
          - weight: 10
            selector:
              expressions:
              - key: cpu
                operator: In
                values:
                - heavy
                - midium
    pod:
      host:
        network: true
      annotations:
      - key: "pod.caicloud.io/feature-1.0.0"
        value: "{'test':'pod'}"
      hostAliases:
      - ip: 192.168.19.0
        hostnames:
        - www.baidu.com
    initContainers:
    - image: mysql-init:v1.0.0
      mounts:
      - name: db-volume
        path: /var/lib/mysql
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
    containers:
    - image: mysql:v5.6
      ports:
      - protocol: TCP
        port: 3306
      mounts:
      - name: db-volume
        path: /var/lib/mysql
      - name: shared-volume
        path: /var/lib/logs
      envFrom:
      - type: Config
        name: someconfigmap
        prefix: XXXX_
        optional: false
      downwardPrefix: MY_ENV
      env:
      - name: XXSS_
        value: "sd"
      - name: Sdsaa
        value: "10"
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
      probe:
        liveness:
          handler:
            type: HTTP
            method:
              port: 80
              path: /liveness
          delay: 10
        readiness:
          handler:
            type: EXEC
            method:
              command:
              - curl
              - http://localhost
          delay: 15
    volumes:
    - name: db-volume
      type: Dedicated
      source:
        class: hdd
        modes:
        - ReadWriteOnce
      storage:
        request: 5Gi
    - name: shared-volume
      type: Dynamic
      source:
        class: ssd
        modes:
        - ReadWriteMany
      storage:
        request: 5Gi
        limit: 100Gi
    services:
    - name: mysql1
      type: ClusterIP
      ports:
      - protocol: HTTP
        targetPort: 80
        port: 80
    - name: mysql2
      type: NodePort
      ports:
      - protocol: HTTPS
        targetPort: 443
        port: 443
        nodePort: 31222
  - type: Deployment
    controller:
      replica: 1
    containers:
    - image: cargo.caicloudprivatetest.com/caicloud/simplelog
      mounts:
      - name: cfgvolume
        path: /etc/simplelog
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
    services:
    - name: log1
      type: ClusterIP
      ports:
      - protocol: HTTP
        targetPort: 80
        port: 80
    volumes:
    - name: test
      type: Scratch
      source:
        medium: "memory"
    - name: cfgvolume
      type: Config
      source:
        target: simplecfg
        items:
        - key: "config.yaml"
          path: "config.yaml"
    configs:
    - name: simplecfg
      data:
      - key: "config.yaml"
        value: |
          sync: "5m"
          deadline: "3h"
    secrets:
    - name: simplesecret
      data:
      - key: "encrypted.cfg"
        value: c3luYzogIjVtIgpkZWFkbGluZTogIjNoIgo=
