_config:
  _metadata:
    name: nginx
    version: 1.13.8
    description: |
      Nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server.
  controllers:
  - type: Deployment
    services:
    - name: nginx
      type: ClusterIP
      export: true
      ports:
      - protocol: HTTP
        targetPort: 80
        port: 80
        nodePort: ''
      - protocol: HTTP
        targetPort: 443
        port: 443
        nodePort: ''
    containers:
    - imagePullPolicy: Always
      image: cargo.caicloudprivatetest.com/library/nginx:1.13.8-alpine
      mounts: []
      env: []
      resources:
        requests:
          cpu: '0.5'
          memory: 0.5Gi
        limits:
          cpu: '0.5'
          memory: 0.5Gi
      ports:
      - protocol: HTTP
        port: 80
      - protocol: HTTP
        port: 443
    volumes: []
