_config:
  _metadata:
    name: kibana
    version: 6.5.4
    description: |
      Kibana is your window into the Elastic Stack. Specifically, it's a browser-based analytics and search dashboard for Elasticsearch.
  controllers:
  - type: Deployment
    controller:
      replica: 1
      strategy:
        type: "RollingUpdate"
      name: kibana
    services:
    - name: kibana
      type: ClusterIP
      ports:
      - protocol: TCP
        targetPort: 5601
        port: 5601
        nodePort: 0
    containers:
    - imagePullPolicy: Always
      image: cargo.caicloudprivatetest.com/library/kibana-oss:6.5.4
      mounts: []
      env:
      - name: ELASTICSEARCH_URL
        value: http://192.168.21.98:9200
      resources:
        requests:
          cpu: '0.1'
          memory: 0.5Gi
        limits:
          cpu: '1'
          memory: 2Gi
      ports:
      - protocol: TCP
        port: 5601
